# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-30 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address1', models.CharField(default='', max_length=254)),
                ('address2', models.CharField(default='', max_length=254)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('town', models.CharField(default='', max_length=254)),
                ('county', models.CharField(default='', max_length=254)),
                ('country', models.CharField(default='', max_length=254)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
