# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address1', models.CharField(default='', max_length=254)),
                ('address2', models.CharField(default='', max_length=254)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('town', models.CharField(default='', max_length=254)),
                ('county', models.CharField(default='', max_length=254)),
                ('country', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
