# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20190723_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='author',
        ),
    ]
