# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-18 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20190718_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('T', 'To Do'), ('P', 'In Progress'), ('C', 'Complete')], default='T', max_length=1),
        ),
    ]
