# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-19 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0003_auto_20190718_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpvoteBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted_bug', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bugs.Bug')),
                ('user_voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
